# Generated by Django 2.1.3 on 2020-09-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pthoto',
            new_name='photo',
        ),
    ]
